// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbaxcdfmrvrnswsrxntl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiYXhjZGZtcnZybnN3c3J4bnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODc1NDIsImV4cCI6MjA2Mzg2MzU0Mn0.8fOZ-GcgbYVYJz4mNk94pdurtdUVQWd33aH5ZyDp34Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);